# Identificadores obrigatórios do SonarCloud 
sonar.organization=josegcaria
sonar.projectKey=JoseGCaria_meu-projeto-devsecops
sonar.projectName=meu-projeto-devsecops
sonar.projectVersion=1.0.0

# Caminhos mapeados para análise
sonar.sources=src
sonar.tests=tests

# Codificação do código-fonte
sonar.sourceEncoding=UTF-8

# Integração com os relatórios de testes e cobertura gerados pelo Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info